// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCekbsJJA8BsbiGKOxek5u7USLLRUr_17c',
    appId: '1:605041481014:web:9ecbf79861ed1755428f97',
    messagingSenderId: '605041481014',
    projectId: 'wssal-4c296',
    authDomain: 'wssal-4c296.firebaseapp.com',
    storageBucket: 'wssal-4c296.appspot.com',
    measurementId: 'G-NE5HFQLK32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBliwIob20-Kmwz1yFKOTpv3M4b6uA6eEc',
    appId: '1:605041481014:android:9a96fa9a0e1c53a6428f97',
    messagingSenderId: '605041481014',
    projectId: 'wssal-4c296',
    storageBucket: 'wssal-4c296.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTRJVmkN3j0N53le6W7nRoFc1ol4eOk08',
    appId: '1:605041481014:ios:0ce93fc31f50a2cb428f97',
    messagingSenderId: '605041481014',
    projectId: 'wssal-4c296',
    storageBucket: 'wssal-4c296.appspot.com',
    iosClientId: '605041481014-l8kqn42pfq000pj5gbnl6monhqt5u407.apps.googleusercontent.com',
    iosBundleId: 'com.wssal.wssal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTRJVmkN3j0N53le6W7nRoFc1ol4eOk08',
    appId: '1:605041481014:ios:0ce93fc31f50a2cb428f97',
    messagingSenderId: '605041481014',
    projectId: 'wssal-4c296',
    storageBucket: 'wssal-4c296.appspot.com',
    iosClientId: '605041481014-l8kqn42pfq000pj5gbnl6monhqt5u407.apps.googleusercontent.com',
    iosBundleId: 'com.wssal.wssal',
  );
}
